=== agatho/uaenhanced/ugaagga/src/config/config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT Config (Header, Languages?, ResourceTypes?, BuildingTypes?, ScienceTypes?, UnitTypes?, DefenseSystemTypes?, EffectTypes?, wonders?, Weathers?, incidentals?, regimes?, Terrains, Regions, Movements)>
<!ELEMENT Header (TakeoverMaxPopularityPoints, TakeoverMinResourceValue, WatchTowerVisionRange, ExposeInvisible, WonderResistance, FuelResourceID, MovementCost, MovementSpeed)>
<!--Languages-->
<!ELEMENT Languages (Language*)>
<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language locale ID #REQUIRED>
<!--Types-->
<!ELEMENT ResourceTypes (Resource*)>
<!ELEMENT BuildingTypes (Building*)>
<!ELEMENT ScienceTypes (Science*)>
<!ELEMENT UnitTypes (Unit*)>
<!ELEMENT DefenseSystemTypes (DefenseSystem*)>
<!ELEMENT Resource (Name+, RatingValue, TakeoverValue, StealRatio, DestroyRatio, SafeStorage, MaxStorage, Production)>
<!ATTLIST Resource id ID #REQUIRED hidden (0 | 1) "0">
<!ELEMENT Building (Name+, Description+, Position?, RatingValue, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Building id ID #REQUIRED hidden (0 | 1) "0">
<!ELEMENT Science (Name+, Description+, Position?, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Science id ID #REQUIRED hidden (0 | 1) "0">
<!ELEMENT Unit (Name+, Description+, Position?, Cost*, ProductionTime, MeleeDamage, RangedDamage, StructuralDamage, MeleeDamageResistance, RangedDamageResistance, HeavyDamageProbability?, CriticalDamageProbability?, Size, Encumbrance*, Visible, Velocity?, FuelUsage?, SpyValue?, SpyChance?, SpyQuality?, AntiSpyChance?, (Requirement | EffectReq)*, WarPoints?)>
<!ATTLIST Unit id ID #REQUIRED hidden (0 | 1) "0">
<!ELEMENT DefenseSystem (Name+, Description+, Position?, Cost*, ProductionTime, MaxDevelopmentLevel, MeleeDamage, RangedDamage, StructuralDamageResistance, HeavyDamageProbability?, CriticalDamageProbability?, Size, AntiSpyChance?, (Requirement | EffectReq)*, WarPoints?)>
<!ATTLIST DefenseSystem id ID #REQUIRED hidden (0 | 1) "0">
<!--Terrains-->
<!ELEMENT Terrains (Terrain+)>
<!ELEMENT Terrain (Name+, Description+, Color, Effect*)>
<!ATTLIST Terrain
          id CDATA #REQUIRED
          takeoverByCombat (0 | 1) "0"
          barren (0 | 1) "0">
<!ELEMENT Color EMPTY>
<!ATTLIST Color r CDATA #REQUIRED g CDATA #REQUIRED b CDATA #REQUIRED>
<!--Regions-->
<!ELEMENT Regions (Region+)>
<!ELEMENT Region (Name+, Description+, Effect*)>
<!ATTLIST Region
          id CDATA #REQUIRED
          startRegion (0 | 1) "0"
          takeoverActivatable (0 | 1) "0"
          barren (0 | 1) "0">
<!--Movements-->
<!ELEMENT Movements (Movement+)>
<!ELEMENT Movement (Name+, Description+, (Requirement | EffectReq)*)>
<!ATTLIST Movement
          id CDATA #REQUIRED
          action (attack|conquer|move|send|spy) #REQUIRED
          speed CDATA #REQUIRED
          provisions CDATA #REQUIRED
          conquering (0 | 1) "0"
          invisible (0 | 1) "0">
<!--Webinterface: Production-->
<!ELEMENT Cost (#PCDATA | object)*>
<!ATTLIST Cost id IDREF #REQUIRED>
<!ELEMENT object EMPTY>
<!ATTLIST object id IDREF #REQUIRED>
<!--Requirement-->
<!ELEMENT Requirement EMPTY>
<!ATTLIST Requirement id IDREF #REQUIRED min CDATA "0" max CDATA #IMPLIED>
<!ELEMENT EffectReq EMPTY>
<!ATTLIST EffectReq id IDREF #REQUIRED min CDATA #IMPLIED max CDATA #IMPLIED>
<!--Encumbrance-->
<!ELEMENT Encumbrance EMPTY>
<!ATTLIST Encumbrance id IDREF #REQUIRED value CDATA #REQUIRED>
<!--Combat-->
<!ELEMENT MeleeDamage (#PCDATA)>
<!ELEMENT RangedDamage (#PCDATA)>
<!ELEMENT StructuralDamage (#PCDATA)>
<!ELEMENT RangedDamageResistance (#PCDATA)>
<!ELEMENT MeleeDamageResistance (#PCDATA)>
<!ELEMENT StructuralDamageResistance (#PCDATA)>
<!ELEMENT HeavyDamageProbability (#PCDATA)>
<!ELEMENT CriticalDamageProbability (#PCDATA)>
<!ELEMENT Size (#PCDATA)>
<!--Effects-->
<!ELEMENT EffectTypes (EffectType*)>
<!ELEMENT EffectType (Name+, Description*)>
<!ATTLIST EffectType id ID #REQUIRED hidden (0 | 1) "0">
<!--wonders-->
<!ELEMENT wonders (wonder+)>
<!ELEMENT wonder (Name+, Description+, chance, impacts+, Cost*, (Requirement | EffectReq)*)>
<!ATTLIST wonder
  offensive (0 | 1) "0"
  target (same | own | other | all) #REQUIRED
  hidden (0 | 1) "0"
  groupID CDATA "0"
>

<!--Wetter-->
<!ELEMENT Weathers (Weather+)>
<!ELEMENT Weather (Name+, we_impacts+)>

<!-- Zufallsereignisse -->
<!ELEMENT incidentals (incidental+)>
<!ELEMENT incidental (Name+, Description+, chance, impacts+)>
<!ATTLIST incidental
  target (same | own | other | all) #REQUIRED
>
<!--Regierungen-->
<!ELEMENT regimes (regime+)>
<!ELEMENT regime (Name+, Description+, impacts+)>
<!ATTLIST regime 
  target (same | own | other | all) #REQUIRED
>
<!--
 target:  (specify allowed target caves)
   same:  the cave, where the spell was casted
   own:   caves, owned by the person, who casted the spell
   other: only caves, that are not owned by the spell caster
   all:   any cave on the map
-->
<!--chance-->
<!ELEMENT chance (#PCDATA | object)*>
<!--impacts-->
<!ELEMENT impacts (impact+)>
<!--impact-->
<!ELEMENT impact (sourceMessage, targetMessage, effects?, resources?, units?, buildings?, sciences?, defenseSystems?)>
<!ATTLIST impact
  delay CDATA #REQUIRED
  duration CDATA #REQUIRED
  steal CDATA "0"
  deactivateTearDown (0 | 1) "0"
>
<!--weather impacts-->
<!ELEMENT we_impacts (we_impact+)>
<!--weather impact-->
<!ELEMENT we_impact (effects?)>
<!ATTLIST we_impact
  delay CDATA #REQUIRED
  duration CDATA #REQUIRED
  steal CDATA "0"
>
<!--
  delay:    time in minutes (delay * base_time_seconds),
            after which the impact takes effect
  duration: time in minutes (duration * base_time_seconds) this impact lasts
-->
<!--messages-->
<!ELEMENT sourceMessage (p*)>
<!ATTLIST sourceMessage
  messageType (none | note | detailed) #REQUIRED
>
<!ELEMENT targetMessage (p*)>
<!ATTLIST targetMessage
  messageType (none | note | detailed) #REQUIRED
>
<!--effects-->
<!ELEMENT effects (effect+)>
<!ATTLIST effects
  all (0 | 1) "0"
>
<!ELEMENT effect EMPTY>
<!ATTLIST effect
  id IDREF #REQUIRED
  absolute CDATA "0"
  relative CDATA "0"
  maxDelta CDATA "0"
  type (default | gauss) "default"
>
<!--
  absolute: absolute value that is added to the actual value
  relative: positive or negative percentage that has to be added
  type:
    default: the values are added exactly as specified
    gauss:   use a gaussian probability distribution around the specified
             values to choose a random number.
             The standard deviation is 1.0 for relative values and
             (0.5 * value) for absolute values
             The resulting random number is cut at 0, so that the return value
             has the same sign as the specified value.
-->
<!--resources-->
<!ELEMENT resources (resource+)>
<!ATTLIST resources
  all (0 | 1) "0"
>
<!ELEMENT resource EMPTY>
<!ATTLIST resource
  id IDREF #REQUIRED
  absolute CDATA "0"
  relative CDATA "0"
  maxDelta CDATA "0"
  type (default | gauss) "default"
>
<!--buildings-->
<!ELEMENT buildings (building+)>
<!ATTLIST buildings
  all (0 | 1) "0"
>
<!ELEMENT building EMPTY>
<!ATTLIST building
  id IDREF #REQUIRED
  absolute CDATA "0"
  relative CDATA "0"
  maxDelta CDATA "0"
  type (default | gauss) "default"
>
<!--units-->
<!ELEMENT units (unit+)>
<!ATTLIST units
  all (0 | 1) "0"
>
<!ELEMENT unit EMPTY>
<!ATTLIST unit
  id IDREF #REQUIRED
  absolute CDATA "0"
  relative CDATA "0"
  maxDelta CDATA "0"
  type (default | gauss) "default"
>
<!--sciences-->
<!ELEMENT sciences (science+)>
<!ATTLIST sciences
  all (0 | 1) "0"
>
<!ELEMENT science EMPTY>
<!ATTLIST science
  id IDREF #REQUIRED
  absolute CDATA "0"
  relative CDATA "0"
  maxDelta CDATA "0"
  type (default | gauss) "default"
>
<!--defenseSystems-->
<!ELEMENT defenseSystems (defenseSystem+)>
<!ATTLIST defenseSystems
  all (0 | 1) "0"
>
<!ELEMENT defenseSystem EMPTY>
<!ATTLIST defenseSystem
  id IDREF #REQUIRED
  absolute CDATA "0"
  relative CDATA "0"
  maxDelta CDATA "0"
  type (default | gauss) "default"
>
<!--Misc-->
<!ELEMENT AntiSpyChance (#PCDATA)>
<!ELEMENT DBFieldName (#PCDATA)>
<!ELEMENT Description (p*)>
<!ATTLIST Description lang IDREF "de_DE">
<!ELEMENT DestroyRatio (#PCDATA)>
<!ELEMENT Effect (#PCDATA)>
<!ATTLIST Effect id IDREF #REQUIRED>
<!ELEMENT ExposeInvisible (#PCDATA | object)*>
<!ELEMENT FuelResourceID (#PCDATA)>
<!ELEMENT FuelUsage (#PCDATA)>
<!ELEMENT MaxDevelopmentLevel (#PCDATA | object)*>
<!ELEMENT SafeStorage (#PCDATA | object)*>
<!ELEMENT MaxStorage (#PCDATA | object)*>
<!ELEMENT MaxValue (#PCDATA)>
<!ELEMENT MovementCost (#PCDATA | object)*>
<!ELEMENT MovementSpeed (#PCDATA | object)*>
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name lang IDREF "de_DE">
<!ELEMENT p (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT ProductionTime (#PCDATA | object)*>
<!ELEMENT RatingValue (#PCDATA)>
<!ELEMENT WarPoints (#PCDATA)>
<!ELEMENT Production (#PCDATA | object)*>
<!ELEMENT SpyQuality (#PCDATA)>
<!ELEMENT SpyChance (#PCDATA)>
<!ELEMENT SpyValue (#PCDATA)>
<!ELEMENT StealRatio (#PCDATA)>
<!ELEMENT TakeoverMaxPopularityPoints (#PCDATA)>
<!ELEMENT TakeoverMinResourceValue (#PCDATA)>
<!ELEMENT TakeoverValue (#PCDATA)>
<!ELEMENT Value (#PCDATA)>
<!ELEMENT Velocity (#PCDATA)>
<!ELEMENT Visible (#PCDATA)>
<!ELEMENT WatchTowerVisionRange (#PCDATA | object)*>
<!ELEMENT WonderResistance (#PCDATA | object)*>
<!--entities-->
<!ENTITY apst "&amp;#39;">
<!ENTITY auml "&amp;auml;">
<!ENTITY ouml "&amp;ouml;">
<!ENTITY uuml "&amp;uuml;">
<!ENTITY Auml "&amp;Auml;">
<!ENTITY Ouml "&amp;Ouml;">
<!ENTITY Uuml "&amp;Uuml;">
<!ENTITY szlig "&amp;szlig;">

=== agatho/uaenhanced/ugaagga/src/config/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Config SYSTEM "config.dtd">
<Config>
  <Header>
    <TakeoverMaxPopularityPoints>1</TakeoverMaxPopularityPoints>
    <TakeoverMinResourceValue>10</TakeoverMinResourceValue>
    <WatchTowerVisionRange>1</WatchTowerVisionRange>
    <ExposeInvisible>0</ExposeInvisible>
    <WonderResistance>0</WonderResistance>
    <FuelResourceID>0</FuelResourceID>
    <MovementCost>1/60</MovementCost>
    <MovementSpeed>30</MovementSpeed>
  </Header>
  <Languages>
    <Language locale="de_DE">Deutsch</Language>
    <Language locale="en_US">English (US)</Language>
  </Languages>
  <ResourceTypes>
    <Resource id="soybean">
      <Name>Sojabohne</Name>
      <Name lang="en_US">Soy Bean</Name>
      <RatingValue>1.0</RatingValue>
      <TakeoverValue>1.0</TakeoverValue>
      <StealRatio>0</StealRatio>
      <DestroyRatio>0</DestroyRatio>
      <SafeStorage>25</SafeStorage>
      <MaxStorage>100</MaxStorage>
      <Production>[acre]</Production>
    </Resource>
  </ResourceTypes>
  <BuildingTypes>
    <Building id="acre">
      <Name>Acker</Name>
      <Name lang="en_US">Farmland</Name>
      <Description>
        <p>Auf dem Acker wachsen Soja-Bohnen, die der Ernährung deiner Bauern dienen.</p>
      </Description>
      <Description lang="en_US">
        <p>Farmland is used to grow soy beans that provide food for your peasants.</p>
      </Description>
      <RatingValue>1</RatingValue>
      <Cost id="soybean">10</Cost>
      <ProductionTime>1440</ProductionTime>
      <MaxDevelopmentLevel>[agriculture]</MaxDevelopmentLevel>
      <Requirement id="agriculture" min="1"/>
    </Building>
  </BuildingTypes>
  <ScienceTypes>
    <Science id="agriculture">
      <Name>Landwirtschaft</Name>
      <Name lang="en_US">Agriculture</Name>
      <Description>
        <p>Nur ein hohes Wissen über die Landwirtschaft beschert reiche Ernten</p>
      </Description>
      <Description lang="en_US">
        <p>If you are learned in agriculture your farmland will yield a large crop.</p>
      </Description>
      <Cost id="soybean">50</Cost>
      <ProductionTime>480</ProductionTime>
      <MaxDevelopmentLevel>100</MaxDevelopmentLevel>
    </Science>
  </ScienceTypes>
  <UnitTypes>
    <Unit id="peasant">
      <Name>Bauer</Name>
      <Name lang="en_US">Peasant</Name>
      <Description>
        <p>Deine Bauern bewirtschaften deine Felder.</p>
      </Description>
      <Description lang="en_US">
        <p>Your peasants will till the soil of your farmland.</p>
      </Description>
      <Cost id="soybean">10</Cost>
      <ProductionTime>120</ProductionTime>
      <MeleeDamage>1</MeleeDamage>
      <RangedDamage>0</RangedDamage>
      <StructuralDamage>0</StructuralDamage>
      <MeleeDamageResistance>1</MeleeDamageResistance>
      <RangedDamageResistance>1</RangedDamageResistance>
      <Size>1</Size>
      <Encumbrance id="soybean" value="1"/>
      <Visible>1</Visible>
      <Velocity>1</Velocity>
      <WarPoints>1</WarPoints>
    </Unit>
  </UnitTypes>
  <DefenseSystemTypes>
    <DefenseSystem id="feeder">
      <Name>Bewässerungsgraben</Name>
      <Name lang="en_US">Irrigation Canal</Name>
      <Description>
        <p>Deine Gräben bewässern die Felder und halten Ungeziefer fern.</p>
      </Description>
      <Description lang="en_US">
        <p>Irrigation canals provide water for your farmland and hold vermin at bay.</p>
      </Description>
      <Cost id="soybean">100</Cost>
      <ProductionTime>720</ProductionTime>
      <MaxDevelopmentLevel>100</MaxDevelopmentLevel>
      <MeleeDamage>0</MeleeDamage>
      <RangedDamage>0</RangedDamage>
      <StructuralDamageResistance>10</StructuralDamageResistance>
      <Size>10</Size>
      <Requirement id="acre" min="1"/>
    </DefenseSystem>
  </DefenseSystemTypes>
  <EffectTypes>
    <EffectType id="population_bonus">
      <Name>Bevölkerungsbonus</Name>
      <Name lang="en_US">Bevölkerungsbonus</Name>
    </EffectType>
    <EffectType id="population_factor">
      <Name>Bevölkerungsfaktor</Name>
      <Name lang="en_US">Bevölkerungsfaktor</Name>
    </EffectType>
    <EffectType id="food_bonus">
      <Name>Nahrungsbonus</Name>
      <Name lang="en_US">Nahrungsbonus</Name>
    </EffectType>
    <EffectType id="food_factor">
      <Name>Nahrungsfaktor</Name>
      <Name lang="en_US">Nahrungsfaktor</Name>
    </EffectType>
    <EffectType id="wood_bonus">
      <Name>Holzbonus</Name>
      <Name lang="en_US">Holzbonus</Name>
    </EffectType>
    <EffectType id="wood_factor">
      <Name>Holzfaktor</Name>
      <Name lang="en_US">Holzfaktor</Name>
    </EffectType>
    <EffectType id="stone_bonus">
      <Name>Steinbonus</Name>
      <Name lang="en_US">Steinbonus</Name>
    </EffectType>
    <EffectType id="stone_factor">
      <Name>Steinfaktor</Name>
      <Name lang="en_US">Steinfaktor</Name>
    </EffectType>
    <EffectType id="metal_bonus">
      <Name>Metallbonus</Name>
      <Name lang="en_US">Metallbonus</Name>
    </EffectType>
    <EffectType id="metal_factor">
      <Name>Metallfaktor</Name>
      <Name lang="en_US">Metallfaktor</Name>
    </EffectType>
    <EffectType id="sulfur_bonus">
      <Name>Schwefelbonus</Name>
      <Name lang="en_US">Schwefelbonus</Name>
    </EffectType>
    <EffectType id="sulfur_factor">
      <Name>Schwefelfaktor</Name>
      <Name lang="en_US">Schwefelfaktor</Name>
    </EffectType>
    <EffectType id="religion_bonus">
      <Name>Gunstbonus</Name>
      <Name lang="en_US">Gunstbonus</Name>
    </EffectType>
    <EffectType id="religion_factor">
      <Name>Gunstfaktor</Name>
      <Name lang="en_US">Gunstfaktor</Name>
    </EffectType>
    <EffectType id="rangeattack_factor">
      <Name>Fernangriffsschadenfaktor</Name>
      <Name lang="en_US">Fernangriffsschadenfaktor</Name>
    </EffectType>
    <EffectType id="arealattack_factor">
      <Name>Gebäudeschadenfaktor</Name>
      <Name lang="en_US">Gebäudeschadenfaktor</Name>
    </EffectType>
    <EffectType id="attackrate_factor">
      <Name>Getümmelschadenfaktor</Name>
      <Name lang="en_US">Getümmelschadenfaktor</Name>
    </EffectType>
    <EffectType id="defenserate_factor">
      <Name>Widerstandspunktefaktor</Name>
      <Name lang="en_US">Widerstandspunktefaktor</Name>
    </EffectType>
    <EffectType id="size_factor">
      <Name>Größenfaktor</Name>
      <Name lang="en_US">Größenfaktor</Name>
    </EffectType>
    <EffectType id="ranged_damage_resistance_factor">
      <Name>Fernkampfwiderstandsfaktor</Name>
      <Name lang="en_US">Fernkampfwiderstandsfaktor</Name>
    </EffectType>
    <EffectType id="movement_cost_factor">
      <Name>Bewegungskostenfaktor</Name>
      <Name lang="en_US">Bewegungskostenfaktor</Name>
    </EffectType>
    <EffectType id="movement_speed_factor">
      <Name>Bewegungsgeschwindigkeitsfaktor</Name>
      <Name lang="en_US">Bewegungsgeschwindigkeitsfaktor</Name>
    </EffectType>
    <EffectType id="long_sight">
      <Name>Weitsicht</Name>
      <Name lang="en_US">Weitsicht</Name>
    </EffectType>
    <EffectType id="expose_invisible">
      <Name>Unsichtbares entdecken</Name>
      <Name lang="en_US">Unsichtbares entdecken</Name>
    </EffectType>
    <EffectType id="wonder_resistance">
      <Name>Wunderresistenz</Name>
      <Name lang="en_US">Wunderresistenz</Name>
    </EffectType>
  </EffectTypes>
  <wonders>
    <wonder offensive="0" target="all">
      <Name>Regentanz</Name>
      <Name lang="en_US">Rain Dance</Name>
      <Description>
        <p>Mit diesem Tanz sollen die Schleusen des Himmels geöffnet werden und so für eine bessere Ernte sorgen.</p>
      </Description>
      <Description lang="en_US">
        <p>The rain dance is a special ceremony that is perfomed to invoke rain.</p>
      </Description>
      <chance>0.01*[agriculture]</chance>
      <impacts>
        <impact delay="5" duration="0">
          <sourceMessage messageType="none"/>
          <targetMessage messageType="detailed">
            <p>Erste Tropfen! Ein Wunder!</p>
          </targetMessage>
          <resources>
            <resource id="soybean" absolute="100" relative="0"/>
          </resources>
        </impact>
      </impacts>
      <Cost id="soybean">50</Cost>
      <Requirement id="agriculture" min="10"/>
    </wonder>
  </wonders>
  <Terrains>
    <Terrain id="0">
      <Name>Ebene</Name>
      <Name lang="en_US">Plains</Name>
      <Description/>
      <Color r="240" g="240" b="192"/>
    </Terrain>
    <Terrain id="1">
      <Name>Wald</Name>
      <Name lang="en_US">Forest</Name>
      <Description/>
      <Color r="192" g="226" b="154"/>
    </Terrain>
    <Terrain id="2">
      <Name>Gebirge</Name>
      <Name lang="en_US">Mountains</Name>
      <Description/>
      <Color r="192" g="192" b="164"/>
    </Terrain>
    <Terrain id="3">
      <Name>Sumpf</Name>
      <Name lang="en_US">Swamp</Name>
      <Description/>
      <Color r="224" g="192" b="152"/>
    </Terrain>
  </Terrains>
  <Regions>
    <Region id="0" startRegion="1" takeoverActivatable="1" barren="0">
      <Name>Irgendwo</Name>
      <Name lang="en_US">Somewhere</Name>
      <Description/>
    </Region>
  </Regions>
  <Movements>
    <Movement id="0" action="send" speed="1" provisions="2" invisible="0">
      <Name>Rohstoffe bringen</Name>
      <Name lang="en_US">Send resources</Name>
      <Description/>
    </Movement>
    <Movement id="1" action="move" speed="1" provisions="1" invisible="0">
      <Name>Einheiten/Rohstoffe verschieben</Name>
      <Name lang="en_US">Move warriors/resources</Name>
      <Description/>
    </Movement>
    <Movement id="2" action="attack" speed="1" provisions="2" invisible="0">
      <Name>Angreifen</Name>
      <Name lang="en_US">Attack</Name>
      <Description/>
    </Movement>
    <Movement id="3" action="spy" speed="1" provisions="2" invisible="1">
      <Name>Spionieren</Name>
      <Name lang="en_US">Espionage</Name>
      <Description/>
    </Movement>
